apiVersion: apps/v1
kind: Deployment
metadata:
        name: server-deployment
spec:
        replicas: 1
        selector:
                matchLabels:
                        component: server
        template:
                metadata:
                        labels:
                                component: server
                spec:
                        containers:
                                - name: server
                                  image: omarlaz/training:server-v1
                                  ports:
                                          - containerPort: 5000
                                  env:
                                          - name: REDIS_HOST
                                            value: redis-cluster-service
                                          - name: REDIS_PORT
                                            value: "6379"
                                          - name: PGUSER
                                            value: postgres
                                          - name: PGHOST
                                            value: postgres-cluster-service
                                          - name: PGPORT
                                            value: "5432"
                                          - name: PGDATABASE
                                            value: postgres
                                          - name: PGPASSWORD
                                            value: postgres_password
---
apiVersion: v1
kind: Service
metadata:
        name: server-cluster-service
spec:
        type: NodePort
        selector:
                component: server
        ports:
                - port: 5000
                  targetPort: 5000
                  nodePort: 31516
